### ISSUE TITLE
App builder migration doesn't update deviceId

### ISSUE THREAD

**Issue by rpeach-sag** [SoftwareAG/cumulocity-migration-tool#16]
Migration of an application-builder dashboard which is linked to a device does not update the deviceId

**Comment by nasr98** [comment]
Is there any workaround/solution to this issue currently? As we think this may be one of the causes of device specific datapoints not being migrated successfully.

**Comment by rpeach-sag** [comment]
Not currently - but give me a couple of hours and i'll fix it now

**Comment by nasr98** [comment]
> 
> 
> Not currently - but give me a couple of hours and i'll fix it now

Many Thanks.

**Comment by rpeach-sag** [comment]
Should be done by the end of the day, it's a little trickier than I remembered

**Comment by rpeach-sag** [comment]
Fixed in [Version 1.1.1](https://github.com/SoftwareAG/cumulocity-migration-tool/releases/tag/v1.1.1)
